apiVersion: v1
kind: Service
metadata:
  name: iot-app
spec:
  type: NodePort
  ports:
  - name: 8888-8888
    nodePort: 8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: iot-app