apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      containers:
      - image: wil42/playground:v1
        name: iot-app
        ports:
        - containerPort: 80